version: '3'

networks:
  network:
    driver: bridge

volumes:
  database:


services:
  proxy:
    image: nginx:latest
    depends_on:
      - client
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    networks:
      - network
  client:
    image: shanth1/client:$CLIENT_VERSION
    depends_on:
      - backend
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000
    networks:
      - network
  backend:
    image: shanth1/server:$SERVER_VERSION
    build: 
      context: ./server
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      PORT: $PORT
      MONGO_URI: $MONGO_URI
      SECRET: $SECRET
      NODE_ENV: $NODE_ENV
    depends_on:
      - database
    ports:
      - 4040
    networks:
      - network
  database:
    image: mongo:4.0-xenial
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWORD
      MONGO_INITDB_DATABASE: quotes
    ports:
      - 27017
    volumes:
      - ./database:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - network



