version: "3"

services:
  nginx:
    image: nginx:v1
    build: ./nginx
    depends_on:
      - frontend
    container_name: nginx
    ports:
      - "80:80"
    networks:
      - mern-network

  frontend:
    image: shanth1/quotes-client:$CLIENT_VERSION
    build: ./client
    container_name: react-ui
    networks:
      - mern-network

    
networks:
  mern-network:
    driver: bridge
