version: '3'

services:
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=/var/www/html --email denisberesnev59@gmail.com --agree-tos --no-eff-email --force-renewal -d quote-it.ru  -d www.quote-it.ru

  nginx:
    image: nginx
    container_name: nginx
    depends_on:
      - frontend
      - backend
    volumes:
      - ./nginx-conf/nginx.conf:/etc/nginx/nginx.conf
      - web-root:/var/www/html
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - dhparam:/etc/ssl/certs
    ports:
      - $PUBLIC_IP:80:80
      - $PUBLIC_IP:443:443
    networks:
      - mern-network

  frontend:
    image: shanth1/quotes-client:$CLIENT_VERSION
    build: ./client
    volumes:
      - web-root:/client/build
    container_name: react-ui
    ports:
      - 8080:3000
    depends_on:
      - backend
    networks:
      - mern-network

  backend:
    image: shanth1/quotes-server:$SERVER_VERSION
    build: ./server
    container_name: node-js
    ports:
      - 10.16.0.1:4040:4040
    depends_on:
      - database
    restart: unless-stopped
    environment:
      MONGO_URI: $MONGO_URI
      SECRET: $SECRET
      NODE_ENV: $NODE_ENV
      PORT: $PORT
    networks:
      - mern-network

  database:
    image: mongo:4.0-xenial
    container_name: mongo-db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWORD
      MONGO_INITDB_DATABASE: quotes
    ports:
      - $PRIVATE_IP:27017:27017
    volumes:
      - ./database:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - mern-network

volumes:
  database:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /home/denis/quoteit/views/
      o: bind
  dhparam:
    driver: local
    driver_opts:
      type: none
      device: /home/denis/quoteit/dhparam/
      o: bind

networks:
  mern-network:
    driver: bridge

# networks:
#   front-tier:
#     external: true
#     name: host
#   back-tier:

  
