mutation RegisterUser($user: UserInput) {
    registerUser(user: $user) {
        id
        firstName
        lastName
        username
        username
        password
        books {
            title
            authors
        }
        quotes {
            text
        }
        createdAt
        updatedAt
    }
}

mutation DeleteUser($userId: ID!) {
    deleteUser(userId: $userId) {
        id
        firstName
        username
    }
}
