query GetAllUsers {
    getAllUsers {
        id
        firstName
        lastName
        username
        password
        books {
            id
            title
        }
        quotes {
            id
            text
        }
        createdAt
        updatedAt
    }
}

query GetUser($userId: ID!) {
    getUser(userId: $userId) {
        id
        firstName
        lastName
        username
        password
        books {
            id
            title
        }
        quotes {
            id
            text
        }
        createdAt
        updatedAt
    }
}

query LoginUser($username: String!, $password: String!) {
    loginUser(username: $username, password: $password) {
        user {
            id
            firstName
            username
        }
        token
    }
}
